In [1]:
import bw2data, bw2io, bw2calc
from bw_timex import TimexLCA
from bw_temporalis import TemporalDistribution, easy_timedelta_distribution
import numpy as np
from datetime import datetime
import os
import re
import pandas as pd
import numpy as np
import pickle

In [2]:
import sys
sys.path.append('../utils/') 
from elec_builder import *

In [3]:
# activate the bw project
bw2data.projects.set_current("ei311")

#del bw2data.databases['']
for db in bw2data.databases:
    print(db, len(bw2data.Database(db)))

In [4]:
bw2data.databases

Databases dictionary with 17 object(s):
	ecoinvent-3.11-biosphere
	ecoinvent-3.11-cutoff
	ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24
	ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22
	ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22
	ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22
	ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22
	ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22
	ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22
	ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22
	ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22
	ei_cutoff_3.11_remind_SSP2-NDC_2030 2025-11-21
	ei_cutoff_3.11_remind_SSP2-NDC_2040 2025-11-21
	ei_cutoff_3.11_remind_SSP2-NDC_2050 2025-11-21
	elec_PV_foreground
	elec_hydro_reservoir_foreground
	elec_wind_foreground

### 1. build up foreground (static)
#### for CN reservoir, using RoW as proxy
#### for US reservoir, using CA-QC as proxy, it's already replaced with Annie's CH4 / CO2 values in AB

##### build only ONE ACT in each database

# for CN reservoir, using RoW as proxy
hydro_qc = ["CA-QC"]
hydro_row = ['RoW']

pathways = [ "SSP1-VLLO" , "SSP2-M", "SSP5-H" ]
years = [2030, 2040, 2050]

for ssp in pathways:
    for year in years:

        fg_db_name = (
                f"elec_hydro_reservoir_foreground_"
                f"CN_{ssp}_{year}"
        )

        act = build_dynamic_electricity_all(
                locations   = hydro_row,
                pathways    = [ssp],    #make sure it's a list 
                years       = [year],   #make sure it's a list 
                elec_act   = "electricity production, hydro, reservoir, non-alpine region",
                ref_name   = "market for electricity, hydro, high voltage",
                fg_db_name = fg_db_name,
                flush_fg_db = True,
        )

# now for US
for ssp in pathways:
    for year in years:

        fg_db_name = (
                f"elec_hydro_reservoir_foreground_"
                f"US_{ssp}_{year}"
        )

        act = build_dynamic_electricity_all(
                locations   = hydro_qc,
                pathways    = [ssp],    #make sure it's a list 
                years       = [year],   #make sure it's a list 
                elec_act   = "electricity production, hydro, reservoir, non-alpine region",
                ref_name   = "market for electricity, hydro, high voltage",
                fg_db_name = fg_db_name,
                flush_fg_db = True,
        )

#### still one final database to check if BW2_timex differs when using ONE-ACT-only Foreground vs. many-ACT Foreground

In [6]:
hydro_all = ["CA-QC", 'RoW']

xx = build_dynamic_electricity_all(
    locations = hydro_all, 
    pathways = [ "SSP1-VLLO" , "SSP2-M", "SSP5-H" ],
    years = [2030, 2040, 2050], 
    elec_act = 'electricity production, hydro, reservoir, non-alpine region',  
    ref_name = 'market for electricity, hydro, high voltage',
    fg_db_name="elec_hydro_reservoir_foreground",
    flush_fg_db = True
)

Flushing existing foreground DB: 'elec_hydro_reservoir_foreground'
Created fresh foreground DB: 'elec_hydro_reservoir_foreground'

In [7]:
hydro_db = bw2data.Database("elec_hydro_reservoir_foreground")
list(hydro_db)

['market for electricity, hydro, high voltage, RoW, SSP2-M, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2040' (kWh, RoW, None)]

In [8]:
len(list(hydro_db))

18

In [9]:
rows = []   # collect results for all acts
act_list = list(hydro_db)   
for act in act_list: 
    print(act)

    name = act.get("name")
    name_parts = [p.strip() for p in name.split(",")]
    # run static LCI + premise_GWP vs. pGWP100 first: 
    pgwp_fixedco2 = find_dpGWP100_method(name_parts[-2], int(name_parts[-1]), method_suffix = "pGWP100 - fixed-AGWPCO2")
    pgwp_dpco2 = find_dpGWP100_method(name_parts[-2], int(name_parts[-1]), method_suffix = "pGWP100 - dp-AGWPCO2")
    gwp =  ('ecoinvent-3.11', 'IPCC 2021 (incl. biogenic CO2)', 'climate change: total (incl. biogenic CO2, incl. SLCFs)', 'global warming potential (GWP100)')   

    lca_gwp = bw2calc.lca.LCA({act: 1}, method=gwp)
    lca_gwp.lci(); lca_gwp.lcia()
    score_gwp = float(lca_gwp.score)

    lca_fixed = bw2calc.lca.LCA({act: 1}, method=pgwp_fixedco2)
    lca_fixed.lci(); lca_fixed.lcia()
    score_fixedco2 = float(lca_fixed.score)

    lca_dp = bw2calc.lca.LCA({act: 1}, method=pgwp_dpco2)
    lca_dp.lci(); lca_dp.lcia()
    score_dpco2 = float(lca_dp.score)

    print(score_gwp, score_fixedco2, score_dpco2) 

    # ---- store results for this activity ----
    rows.append({
        "Activity": name,                      # index value later
        "gwp100": score_gwp,
        "pGWP100_fixedCO2": score_fixedco2,
        "pGWP100_dpCO2": score_dpco2,
    })

'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None)
0.027237480987037516 0.03158437928431752 0.02711969689287509
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None)
0.05076620089003004 0.06826572518730606 0.04941494612487993
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2040' (kWh, CA-QC, None)
0.015677933911314414 0.020513518225509387 0.015532795585280867
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None)
0.025149297413734607 0.025654805949944928 0.026053074236294882
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None)
0.047436732219881 0.047269481689540434 0.04806139092343953
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None)
0.050624132429712226 0.0588433577155799 0.05050087185795245
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2040' (kWh, CA-QC, None)
0.015027617823721764 0.014985699463817273 0.015085692888404051
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2040' (kWh, RoW, None)
0.05016714038066257 0.05568431794755916 0.05028691672475139
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2040' (kWh, CA-QC, None)
0.015561841109323798 0.01723492824558421 0.015565662778805642
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2040' (kWh, RoW, None)
0.050594952887580834 0.06531290369272466 0.04947780219892701
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None)
0.050387932655764876 0.06134299794678142 0.049512357602919665
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None)
0.049843677135038844 0.05280472422916528 0.05014361486936589
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None)
0.026951855317342496 0.028854861070076166 0.02740915075753975
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)
0.05052327410460818 0.05187732398980784 0.050840890431154896
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2040' (kWh, RoW, None)
0.048724343697182676 0.048975230317371596 0.049294279340788276
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None)
0.027212423874515414 0.028280785292983297 0.027694732474946575
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None)
0.027073917467990385 0.03204242896885204 0.025918992373042765
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None)
0.02729293993288841 0.03515319702658596 0.02549412490809645

In [10]:
df_scores = pd.DataFrame(rows)
df_scores = df_scores.set_index("Activity")

df2 = df_scores.sort_values(by=['Activity'])
df2

,gwp100,pGWP100_fixedCO2,pGWP100_dpCO2
Activity,,,
"market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030",0.027212,0.028281,0.027695
"market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2040",0.015028,0.014986,0.015086
"market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050",0.025149,0.025655,0.026053
"market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030",0.027237,0.031584,0.027120
"market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2040",0.015562,0.017235,0.015566
"market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050",0.026952,0.028855,0.027409
"market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030",0.027293,0.035153,0.025494
"market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2040",0.015678,0.020514,0.015533
"market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050",0.027074,0.032042,0.025919
"market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030",0.050523,0.051877,0.050841
"market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2040",0.048724,0.048975,0.049294
"market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050",0.047437,0.047269,0.048061
"market for electricity, hydro, high voltage, RoW, SSP2-M, 2030",0.050624,0.058843,0.050501
"market for electricity, hydro, high voltage, RoW, SSP2-M, 2040",0.050167,0.055684,0.050287
"market for electricity, hydro, high voltage, RoW, SSP2-M, 2050",0.049844,0.052805,0.050144
"market for electricity, hydro, high voltage, RoW, SSP5-H, 2030",0.050766,0.068266,0.049415
"market for electricity, hydro, high voltage, RoW, SSP5-H, 2040",0.050595,0.065313,0.049478
"market for electricity, hydro, high voltage, RoW, SSP5-H, 2050",0.050388,0.061343,0.049512

In [11]:
df2.index = df2.index.str.replace("RoW", "CN", regex=False)
df2.index = df2.index.str.replace("CA-QC", "US", regex=False)
df2

,gwp100,pGWP100_fixedCO2,pGWP100_dpCO2
Activity,,,
"market for electricity, hydro, high voltage, US, SSP1-VLLO, 2030",0.027212,0.028281,0.027695
"market for electricity, hydro, high voltage, US, SSP1-VLLO, 2040",0.015028,0.014986,0.015086
"market for electricity, hydro, high voltage, US, SSP1-VLLO, 2050",0.025149,0.025655,0.026053
"market for electricity, hydro, high voltage, US, SSP2-M, 2030",0.027237,0.031584,0.027120
"market for electricity, hydro, high voltage, US, SSP2-M, 2040",0.015562,0.017235,0.015566
"market for electricity, hydro, high voltage, US, SSP2-M, 2050",0.026952,0.028855,0.027409
"market for electricity, hydro, high voltage, US, SSP5-H, 2030",0.027293,0.035153,0.025494
"market for electricity, hydro, high voltage, US, SSP5-H, 2040",0.015678,0.020514,0.015533
"market for electricity, hydro, high voltage, US, SSP5-H, 2050",0.027074,0.032042,0.025919
"market for electricity, hydro, high voltage, CN, SSP1-VLLO, 2030",0.050523,0.051877,0.050841
"market for electricity, hydro, high voltage, CN, SSP1-VLLO, 2040",0.048724,0.048975,0.049294
"market for electricity, hydro, high voltage, CN, SSP1-VLLO, 2050",0.047437,0.047269,0.048061
"market for electricity, hydro, high voltage, CN, SSP2-M, 2030",0.050624,0.058843,0.050501
"market for electricity, hydro, high voltage, CN, SSP2-M, 2040",0.050167,0.055684,0.050287
"market for electricity, hydro, high voltage, CN, SSP2-M, 2050",0.049844,0.052805,0.050144
"market for electricity, hydro, high voltage, CN, SSP5-H, 2030",0.050766,0.068266,0.049415
"market for electricity, hydro, high voltage, CN, SSP5-H, 2040",0.050595,0.065313,0.049478
"market for electricity, hydro, high voltage, CN, SSP5-H, 2050",0.050388,0.061343,0.049512

In [12]:
df2.to_excel("dp-LCI_output/staticLCI_(p)GWP100/hydro_reservoir_CN-asRoW_US-asQC_staticLCI_threeGWP100.xlsx")

### 2. building dpLCI

In [13]:
#hydro_db = bw2data.Database("elec_hydro_reservoir_foreground")
len(list(hydro_db))

18

In [14]:
hydro_db_203050 = [
    act for act in hydro_db 
    if "2050" in str(act.get('name', '')) or  "2030" in str(act.get('name', ''))
]
len(list(hydro_db_203050))

12

#### .static_score is the full dpLCI but with non-dyn LCIA 
#### .base_score is the dyn-foreground LCI only (static background LCI) but with non-dyn LCIA

In [15]:
database_dates = {
    'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.strptime("2030", "%Y"),
    'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.strptime("2040", "%Y"),
    'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.strptime("2050", "%Y"),

    'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.strptime("2030", "%Y"),
    'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.strptime("2040", "%Y"),
    'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.strptime("2050", "%Y"),

    'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.strptime("2030", "%Y"),
    'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.strptime("2040", "%Y"),
    'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.strptime("2050", "%Y"),
    
    "elec_hydro_reservoir_foreground": "dynamic", # flag databases that should be temporally distributed with "dynamic"
}

In [16]:
find_dpGWP100_method('SSP1-VLLO', 2030, method_suffix = "pGWP100 - dp-AGWPCO2")

('Climate Change prospective GWP100',
 'SSP119',
 'MY2030',
 'pGWP100 - dp-AGWPCO2')

In [17]:
dp_results = {}

for act in list(hydro_db_203050): 
    print(act)
 
    #### dynamic LCI:: 
    assign_td_from_foreground_db( 
        select_act = act,
        elec_td_year=10,
        resolution="Y",
        kind="uniform",
        fg_db_name="elec_hydro_reservoir_foreground",
        verbose = True
     )

    tlca = run_dp_timex_lca(foreground_act = act ,   
                    pathway = None,
                    year = None,
                    method = None,
                    database_dates = database_dates, #None not working, has to incl. all 9 background DB ... 
                    temporal_grouping="year", 
                    method_prefix = "Climate Change prospective GWP100",
                    method_suffix = "pGWP100 - fixed-AGWPCO2", 
                    fg_db_name = 'elec_hydro_reservoir_foreground'
     )

    tlca.lci()
    tlca.dynamic_inventory.shape

    # dyn-foreground LCI + static background LCI + pGWP100
    lca_0 = tlca.base_score 
    print(lca_0)
    # dpLCI (dyn-foreground LCI + dyn background LCI) +  pGWP100
    tlca.static_lcia()
    lca_1 = tlca.static_score
    print(lca_1)

    act_name = act.get("name")
    dp_results[act_name] = {
        "dyn FG LCI static BG p-LCI, pGWP100-fixedCO2": float(lca_0),   # static BG LCI + dyn FG LCI
        "full dp-LCI, pGWP100-fixedCO2": float(lca_1),      # dyn BG LCI + dyn FG LCI
    }

    #### now save all dyLCI flows to pandas 
    df = tlca.dynamic_inventory_df

    ##### important to convert flow and act as str to excel 
    df["flow"] = df["flow"].astype(str)
    df["activity"] = df["activity"].astype(str)

    ### export df to dp-LCI_output folder, using the act name as the excel name 
    out_dir = "dp-LCI_output/hydro_dpLCI_reservoir"
    os.makedirs(out_dir, exist_ok=True)    
    raw_name = act["name"]
    safe_name = re.sub(r"[^A-Za-z0-9_\-()]+", "_", raw_name)   # replace spaces/special chars
    
    excel_path = os.path.join(out_dir, f"{safe_name}.xlsx")
    
    df.to_excel(excel_path, index=False)    
    print(f"✔ Exported dynamic inventory DF for '{raw_name}' → {excel_path}")


import pickle

out_dir = "dp-LCI_output/hydro_dpLCI_reservoir"
os.makedirs(out_dir, exist_ok=True)

pickle_path = os.path.join(out_dir, "hydro_reservoir_dp_results_MY2030_2050.pkl")

with open(pickle_path, "wb") as f:
    pickle.dump(dp_results, f)

print(f"✔ Saved dp_results dictionary → {pickle_path}")

2026-03-30 10:21:07.316 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 10:21:07.318 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None),it's under SSP-SSP1-VLLO, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 10:23:47.204 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 10:24:46.900 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 10:24:57.287 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 10:24:59.818 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 10:25:01.630 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2026-03-30 10:25:01.767 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:25:01.768 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:25:01.769 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:25:01.775 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:25:01.778 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2026-03-30 10:25:16.121 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 10:25:16.257 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.05187732398980784
0.052091532866825434

2026-03-30 10:25:58.782 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 10:25:58.784 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP1-VLLO_2030.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None),it's under SSP-SSP2-M, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 10:29:32.087 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 10:33:38.414 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 10:34:02.812 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 10:34:05.429 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 10:34:07.271 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2026-03-30 10:34:07.414 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:34:07.416 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:34:07.419 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:34:07.422 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:34:07.423 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:34:39.895 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 10:34:39.965 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.03158437928431752
0.029088294397407538

2026-03-30 10:35:20.713 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 10:35:20.714 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP2-M_2030.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None),it's under SSP-SSP2-M, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 10:40:36.857 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 10:43:39.420 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 10:44:02.982 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 10:44:06.113 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 10:44:07.959 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2026-03-30 10:44:08.103 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:44:08.106 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:44:08.107 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:44:08.108 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:44:08.109 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:44:42.645 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 10:44:42.811 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.028854861070076166
0.026792195379353005

2026-03-30 10:45:25.587 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 10:45:25.590 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP2-M_2050.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None),it's under SSP-SSP1-VLLO, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 10:49:44.930 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 10:53:39.055 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 10:54:03.319 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 10:54:06.300 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 10:54:08.073 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2026-03-30 10:54:08.177 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:54:08.181 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:54:08.182 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:54:08.183 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 10:54:08.186 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2026-03-30 10:54:41.579 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 10:54:41.652 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.028280785292983297
0.02600650846396627

2026-03-30 10:55:25.425 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 10:55:25.427 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP1-VLLO_2030.xlsx
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None),it's under SSP-SSP2-M, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 10:59:38.419 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 11:04:17.982 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 11:04:42.249 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 11:04:45.076 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 11:04:46.723 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2026-03-30 11:04:46.851 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:04:46.853 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:04:46.854 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:04:46.855 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:04:46.857 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2026-03-30 11:05:26.620 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 11:05:26.743 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.0588433577155799
0.05897109878407706

2026-03-30 11:06:07.523 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 11:06:07.525 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP2-M_2030.xlsx
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None),it's under SSP-SSP5-H, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 11:10:04.744 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 11:14:07.430 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 11:14:32.840 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 11:14:35.730 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 11:14:38.066 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2026-03-30 11:14:38.199 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:14:38.202 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:14:38.203 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:14:38.206 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:14:38.207 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:15:18.146 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 11:15:18.249 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.06134299794678142
0.061760500173898024

2026-03-30 11:16:01.715 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 11:16:01.716 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP5-H_2050.xlsx
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None),it's under SSP-SSP2-M, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 11:20:55.558 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 11:24:02.959 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 11:24:26.204 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 11:24:28.924 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 11:24:30.961 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2026-03-30 11:24:31.071 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:24:31.073 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:24:31.074 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:24:31.075 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:24:31.076 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2026-03-30 11:25:05.461 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 11:25:05.649 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.05280472422916528
0.053736865699996486

2026-03-30 11:26:17.355 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 11:26:17.356 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP2-M_2050.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None),it's under SSP-SSP5-H, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 11:30:04.885 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 11:34:17.547 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 11:34:41.041 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 11:34:44.155 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 11:34:46.416 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2026-03-30 11:34:46.553 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:34:46.556 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:34:46.559 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:34:46.562 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:34:46.565 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:35:19.562 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 11:35:19.730 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.03204242896885204
0.029823149250897112

2026-03-30 11:36:04.365 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 11:36:04.367 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP5-H_2050.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None),it's under SSP-SSP1-VLLO, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 11:40:28.269 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 11:45:13.135 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 11:45:43.236 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 11:45:46.805 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 11:45:48.818 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2026-03-30 11:45:48.982 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:45:48.983 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:45:48.985 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:45:48.987 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:45:48.990 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:46:30.824 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 11:46:31.050 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.025654805949944928
0.025416003239339482

2026-03-30 11:47:18.391 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 11:47:18.396 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP1-VLLO_2050.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None),it's under SSP-SSP5-H, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 11:52:58.861 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 11:55:49.522 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 11:56:15.115 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 11:56:18.013 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 11:56:19.928 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2026-03-30 11:56:20.103 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:56:20.105 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:56:20.107 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:56:20.109 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:56:20.110 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 11:57:00.848 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 11:57:01.030 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.03515319702658596
0.03253244995622028

2026-03-30 11:57:45.248 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 11:57:45.251 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP5-H_2030.xlsx
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None),it's under SSP-SSP1-VLLO, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 12:02:38.850 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 12:06:02.969 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 12:06:27.386 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 12:06:30.212 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 12:06:32.045 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2026-03-30 12:06:32.173 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:06:32.177 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:06:32.178 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:06:32.181 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:06:32.184 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2026-03-30 12:07:17.609 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 12:07:17.771 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.047269481689540434
0.05050874993532154

2026-03-30 12:08:33.894 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2026-03-30 12:08:33.896 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP1-VLLO_2050.xlsx
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None),it's under SSP-SSP5-H, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2026-03-30 12:13:20.171 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2026-03-30 12:16:18.148 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2026-03-30 12:16:48.763 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2026-03-30 12:16:52.484 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2026-03-30 12:16:54.697 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2026-03-30 12:16:54.863 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:16:54.865 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:16:54.866 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:16:54.868 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:16:54.869 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-03-30 12:17:37.721 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2026-03-30 12:17:37.850 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.06826572518730606
0.0682226996752618
✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP5-H_2030.xlsx
✔ Saved dp_results dictionary → dp-LCI_output/hydro_dpLCI_reservoir/hydro_reservoir_dp_results_MY2030_2050.pkl