In [1]:
import bw2data, bw2io, bw2calc
from bw_timex import TimexLCA
from bw_temporalis import TemporalDistribution, easy_timedelta_distribution
import numpy as np
from datetime import datetime
import os
import re
import pandas as pd
import numpy as np
import pickle

In [2]:
import sys
sys.path.append('../utils/') 
from elec_builder import *

In [3]:
# activate the bw project
bw2data.projects.set_current("ei311")
#for db in bw2data.databases:
#    print(db, len(bw2data.Database(db)))

#### for CN reservoir, using RoW as proxy
#### for US reservoir, using CA-QC as proxy

In [4]:
#hydro_cn = ['CN-SC']

# for CN reservoir, using RoW as proxy
hydro_us = ['US-WECC']
hydro_qc = ["CA-QC"]
hydro_row = ['RoW']

xx = build_dynamic_electricity_all(
    locations = hydro_row , 
    pathways = [ "SSP1-VLLO" , "SSP2-M", "SSP5-H" ],
    years = [2030, 2040, 2050], 
    elec_act = 'electricity production, hydro, reservoir, non-alpine region', #'electricity production, hydro, run-of-river',
    ref_name = 'market for electricity, hydro, high voltage',
    fg_db_name="elec_hydro_reservoir_foreground",
    flush_fg_db = True
)

# not tested: assign_td_from_results_dict(results_dict = xx, elec_td_year=10)

pathways should match the premise database names, e.g., SSP1-VLLO, SSP2-M, SSP5-H
 also IAM locations for premise database can be found through calling:
 from premise import geomap -> premise.geomap.Geomap('image').iam_regions
Created fresh foreground DB: 'elec_hydro_reservoir_foreground'

In [5]:
yy =  build_dynamic_electricity_all(
    locations = hydro_qc,
    pathways = [ "SSP1-VLLO" , "SSP2-M", "SSP5-H" ],
    years = [2030, 2040, 2050], 
    elec_act = 'electricity production, hydro, reservoir, non-alpine region',
    ref_name = 'market for electricity, hydro, high voltage',
    fg_db_name="elec_hydro_reservoir_foreground",
    flush_fg_db = False
)

pathways should match the premise database names, e.g., SSP1-VLLO, SSP2-M, SSP5-H
 also IAM locations for premise database can be found through calling:
 from premise import geomap -> premise.geomap.Geomap('image').iam_regions
Using foreground DB: elec_hydro_reservoir_foreground, with 9 activities currently.

In [6]:
hydro_db = bw2data.Database("elec_hydro_reservoir_foreground")
len(hydro_db)

18

In [7]:
list(hydro_db)

['market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None)]

In [8]:
act_list = list(hydro_db)[2:4]
for act in act_list:
    tech_excs = list(act.technosphere())
    print(len(tech_excs))
    exc = tech_excs[0]
    print(exc)

1
Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)>
1
Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2040' (kWh, RoW, None)>

In [9]:
rows = []   # collect results for all acts
act_list = list(hydro_db)   
for act in act_list: 
    print(act)

    name = act.get("name")
    name_parts = [p.strip() for p in name.split(",")]
    # run static LCI + premise_GWP vs. pGWP100 first: 
    pgwp_fixedco2 = find_dpGWP100_method(name_parts[-2], int(name_parts[-1]), method_suffix = "pGWP100 - fixed-AGWPCO2")
    pgwp_dpco2 = find_dpGWP100_method(name_parts[-2], int(name_parts[-1]), method_suffix = "pGWP100 - dp-AGWPCO2")
    gwp =  ('ecoinvent-3.11', 'IPCC 2021 (incl. biogenic CO2)', 'climate change: total (incl. biogenic CO2, incl. SLCFs)', 'global warming potential (GWP100)')   

    lca_gwp = bw2calc.lca.LCA({act: 1}, method=gwp)
    lca_gwp.lci(); lca_gwp.lcia()
    score_gwp = float(lca_gwp.score)

    lca_fixed = bw2calc.lca.LCA({act: 1}, method=pgwp_fixedco2)
    lca_fixed.lci(); lca_fixed.lcia()
    score_fixedco2 = float(lca_fixed.score)

    lca_dp = bw2calc.lca.LCA({act: 1}, method=pgwp_dpco2)
    lca_dp.lci(); lca_dp.lcia()
    score_dpco2 = float(lca_dp.score)

    print(score_gwp, score_fixedco2, score_dpco2) 

    # ---- store results for this activity ----
    rows.append({
        "Activity": name,                      # index value later
        "gwp100": score_gwp,
        "pGWP100_fixedCO2": score_fixedco2,
        "pGWP100_dpCO2": score_dpco2,
    })

'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None)
0.0506240716426115 0.05584781277644521 0.04991070284626162
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2040' (kWh, RoW, None)
0.05016714038066257 0.05256302093778377 0.04990881578455679
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None)
0.0158012883553034 0.017236325178465225 0.015666238870664376
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2040' (kWh, RoW, None)
0.050594952887580834 0.04985878762114201 0.04968123964054657
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None)
0.04984364079505242 0.04970101534488699 0.04993021028670728
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None)
0.04743668155690239 0.05397877348149437 0.04740237046169956
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2040' (kWh, CA-QC, None)
0.015561841109323798 0.016342932251011334 0.015521869353196324
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None)
0.050387884419407156 0.04519814216649301 0.050005979586170334
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None)
0.015460680055796176 0.015388249048912811 0.01546214441738055
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None)
0.015720732558650957 0.017909496424950364 0.015649619649950153
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2040' (kWh, CA-QC, None)
0.015677933911314414 0.015612622816426731 0.015559221898336563
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None)
0.013657874906730162 0.015534852035032371 0.01364607085120712
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None)
0.01558249037485818 0.014036297672589812 0.015528179132344836
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2040' (kWh, RoW, None)
0.048724343697182676 0.05504079781454591 0.048587313819745494
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)
0.05052321158674736 0.05726559498803554 0.05002123263004093
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None)
0.05076614048384639 0.05473730101033961 0.04973538862760401
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2040' (kWh, CA-QC, None)
0.015027617823721764 0.016988363397679975 0.015003071350999401
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None)
0.015745826396561434 0.017505039575352998 0.015649436667127252

In [10]:
df_scores = pd.DataFrame(rows)
df_scores = df_scores.set_index("Activity")

df2 = df_scores.sort_values(by=['Activity'])
df2

,gwp100,pGWP100_fixedCO2,pGWP100_dpCO2
Activity,,,
"market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030",0.015721,0.017909,0.015650
"market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2040",0.015028,0.016988,0.015003
"market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050",0.013658,0.015535,0.013646
"market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030",0.015746,0.017505,0.015649
"market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2040",0.015562,0.016343,0.015522
"market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050",0.015461,0.015388,0.015462
"market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030",0.015801,0.017236,0.015666
"market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2040",0.015678,0.015613,0.015559
"market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050",0.015582,0.014036,0.015528
"market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030",0.050523,0.057266,0.050021
"market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2040",0.048724,0.055041,0.048587
"market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050",0.047437,0.053979,0.047402
"market for electricity, hydro, high voltage, RoW, SSP2-M, 2030",0.050624,0.055848,0.049911
"market for electricity, hydro, high voltage, RoW, SSP2-M, 2040",0.050167,0.052563,0.049909
"market for electricity, hydro, high voltage, RoW, SSP2-M, 2050",0.049844,0.049701,0.049930
"market for electricity, hydro, high voltage, RoW, SSP5-H, 2030",0.050766,0.054737,0.049735
"market for electricity, hydro, high voltage, RoW, SSP5-H, 2040",0.050595,0.049859,0.049681
"market for electricity, hydro, high voltage, RoW, SSP5-H, 2050",0.050388,0.045198,0.050006

In [12]:
df2.index = df2.index.str.replace("RoW", "CN", regex=False)
df2.index = df2.index.str.replace("CA-QC", "US", regex=False)
df2

,gwp100,pGWP100_fixedCO2,pGWP100_dpCO2
Activity,,,
"market for electricity, hydro, high voltage, US, SSP1-VLLO, 2030",0.015721,0.017909,0.015650
"market for electricity, hydro, high voltage, US, SSP1-VLLO, 2040",0.015028,0.016988,0.015003
"market for electricity, hydro, high voltage, US, SSP1-VLLO, 2050",0.013658,0.015535,0.013646
"market for electricity, hydro, high voltage, US, SSP2-M, 2030",0.015746,0.017505,0.015649
"market for electricity, hydro, high voltage, US, SSP2-M, 2040",0.015562,0.016343,0.015522
"market for electricity, hydro, high voltage, US, SSP2-M, 2050",0.015461,0.015388,0.015462
"market for electricity, hydro, high voltage, US, SSP5-H, 2030",0.015801,0.017236,0.015666
"market for electricity, hydro, high voltage, US, SSP5-H, 2040",0.015678,0.015613,0.015559
"market for electricity, hydro, high voltage, US, SSP5-H, 2050",0.015582,0.014036,0.015528
"market for electricity, hydro, high voltage, CN, SSP1-VLLO, 2030",0.050523,0.057266,0.050021
"market for electricity, hydro, high voltage, CN, SSP1-VLLO, 2040",0.048724,0.055041,0.048587
"market for electricity, hydro, high voltage, CN, SSP1-VLLO, 2050",0.047437,0.053979,0.047402
"market for electricity, hydro, high voltage, CN, SSP2-M, 2030",0.050624,0.055848,0.049911
"market for electricity, hydro, high voltage, CN, SSP2-M, 2040",0.050167,0.052563,0.049909
"market for electricity, hydro, high voltage, CN, SSP2-M, 2050",0.049844,0.049701,0.049930
"market for electricity, hydro, high voltage, CN, SSP5-H, 2030",0.050766,0.054737,0.049735
"market for electricity, hydro, high voltage, CN, SSP5-H, 2040",0.050595,0.049859,0.049681
"market for electricity, hydro, high voltage, CN, SSP5-H, 2050",0.050388,0.045198,0.050006

In [13]:
df2.to_excel("dp-LCI_output/staticLCI_(p)GWP100/hydro_reservoir_CN-asRoW_US-asQC_staticLCI_threeGWP100.xlsx")

### 2. building dpLCI

In [4]:
hydro_db = bw2data.Database("elec_hydro_reservoir_foreground")
list(hydro_db)

['market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2040' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2040' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None)]

In [5]:
hydro_db_203050 = [
    act for act in hydro_db 
    if "2050" in str(act.get('name', '')) or  "2030" in str(act.get('name', ''))
]

hydro_db_203050

['market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None),
 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None),
 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)]

In [8]:
database_dates = {
    'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.strptime("2030", "%Y"),
    'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.strptime("2040", "%Y"),
    'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.strptime("2050", "%Y"),

    'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.strptime("2030", "%Y"),
    'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.strptime("2040", "%Y"),
    'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.strptime("2050", "%Y"),

    'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.strptime("2030", "%Y"),
    'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.strptime("2040", "%Y"),
    'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.strptime("2050", "%Y"),
    
    "elec_hydro_reservoir_foreground": "dynamic", # flag databases that should be temporally distributed with "dynamic"
}

find_dpGWP100_method('SSP1-VLLO', 2030, method_suffix = "pGWP100 - dp-AGWPCO2")

In [9]:
dp_results = {}

for act in list(hydro_db_203050): 
    print(act)
 
    #### dynamic LCI:: 
    assign_td_from_foreground_db( 
        select_act = act,
        elec_td_year=10,
        resolution="Y",
        kind="uniform",
        fg_db_name="elec_hydro_reservoir_foreground",
        verbose = True
     )

    tlca = run_dp_timex_lca(foreground_act = act ,   
                    pathway = None,
                    year = None,
                    method = None,
                    database_dates = database_dates, #None not working, has to incl. all 9 background DB ... 
                    temporal_grouping="year", 
                    method_prefix = "Climate Change prospective GWP100",
                    method_suffix = "pGWP100 - fixed-AGWPCO2", 
                    fg_db_name = 'elec_hydro_reservoir_foreground'
     )

    tlca.lci()
    tlca.dynamic_inventory.shape

    # dyn-foreground LCI + static background LCI + pGWP100
    lca_0 = tlca.base_score 
    print(lca_0)
    # dpLCI (dyn-foreground LCI + dyn background LCI) +  pGWP100
    tlca.static_lcia()
    lca_1 = tlca.static_score
    print(lca_1)

    act_name = act.get("name")
    dp_results[act_name] = {
        "dyn FG LCI static BG p-LCI, pGWP100-fixedCO2": float(lca_0),   # static BG LCI + dyn FG LCI
        "full dp-LCI, pGWP100-fixedCO2": float(lca_1),      # dyn BG LCI + dyn FG LCI
    }

    #### now save all dyLCI flows to pandas 
    df = tlca.dynamic_inventory_df

    ##### important to convert flow and act as str to excel 
    df["flow"] = df["flow"].astype(str)
    df["activity"] = df["activity"].astype(str)

    ### export df to dp-LCI_output folder, using the act name as the excel name 
    out_dir = "dp-LCI_output/hydro_dpLCI_v2_reservoir"
    os.makedirs(out_dir, exist_ok=True)    
    raw_name = act["name"]
    safe_name = re.sub(r"[^A-Za-z0-9_\-()]+", "_", raw_name)   # replace spaces/special chars
    
    excel_path = os.path.join(out_dir, f"{safe_name}.xlsx")
    
    df.to_excel(excel_path, index=False)    
    print(f"✔ Exported dynamic inventory DF for '{raw_name}' → {excel_path}")


import pickle

out_dir = "dp-LCI_output/hydro_dpLCI_v2_reservoir"
os.makedirs(out_dir, exist_ok=True)

pickle_path = os.path.join(out_dir, "hydro_v2_reservoir_dp_results_MY2030_2050.pkl")

with open(pickle_path, "wb") as f:
    pickle.dump(dp_results, f)

print(f"✔ Saved dp_results dictionary → {pickle_path}")

2025-12-11 19:04:22.528 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 19:04:22.528 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' (kWh, RoW, None),it's under SSP-SSP1-VLLO, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 19:08:04.689 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 19:09:50.328 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 19:10:26.260 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 19:10:29.719 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 19:10:31.734 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 19:10:31.996 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:10:31.997 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:10:31.998 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:10:31.999 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:10:32.001 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:10:41.753 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 19:10:41.839 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.05397877348149437
0.057713978323068696

2025-12-11 19:11:38.240 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 19:11:38.242 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP1-VLLO_2050.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' (kWh, CA-QC, None),it's under SSP-SSP1-VLLO, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 19:16:18.159 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 19:20:16.509 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 19:20:47.201 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 19:20:50.853 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 19:20:52.865 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 19:20:53.052 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:20:53.053 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:20:53.053 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:20:53.054 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:20:53.056 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:21:27.476 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 19:21:27.556 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.017909496424950364
0.017974606532037102

2025-12-11 19:22:22.896 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 19:22:22.899 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP1-VLLO_2030.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' (kWh, CA-QC, None),it's under SSP-SSP2-M, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 19:27:30.129 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 19:33:05.145 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 19:33:32.147 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 19:33:35.356 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 19:33:37.361 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 19:33:37.742 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:33:37.745 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:33:37.752 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:33:37.756 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:33:37.758 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:34:17.828 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 19:34:17.920 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.017505039575352998
0.017540590280462082

2025-12-11 19:35:11.381 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 19:35:11.382 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP2-M_2030.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' (kWh, CA-QC, None),it's under SSP-SSP5-H, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 19:41:48.473 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 19:47:04.093 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 19:47:30.283 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 19:47:33.320 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 19:47:35.166 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 19:47:35.380 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:47:35.381 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:47:35.382 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:47:35.384 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:47:35.386 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:48:09.431 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 19:48:09.544 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.014036297672589812
0.014211350765469078

2025-12-11 19:49:17.459 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 19:49:17.461 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP5-H_2050.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' (kWh, CA-QC, None),it's under SSP-SSP5-H, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 19:53:58.462 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 19:58:52.596 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 19:59:16.925 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 19:59:19.673 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 19:59:21.488 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 19:59:21.678 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:59:21.679 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:59:21.680 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:59:21.682 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 19:59:21.687 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:00:03.155 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 20:00:03.261 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.017236325178465225
0.01721101032412986

2025-12-11 20:00:55.268 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 20:00:55.272 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP5-H, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP5-H_2030.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' (kWh, CA-QC, None),it's under SSP-SSP2-M, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 20:06:06.931 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 20:12:24.972 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 20:12:50.601 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 20:12:53.396 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 20:12:55.050 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2025-12-11 20:12:55.177 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:12:55.178 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:12:55.180 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:12:55.181 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:12:55.183 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2025-12-11 20:13:39.876 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 20:13:39.997 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.015388249048912811
0.015701920111674168

2025-12-11 20:14:34.867 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 20:14:34.869 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP2-M, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP2-M_2050.xlsx
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' (kWh, RoW, None),it's under SSP-SSP5-H, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 20:20:13.287 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 20:25:06.864 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 20:25:31.840 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 20:25:34.602 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 20:25:36.504 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2025-12-11 20:25:36.624 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:25:36.624 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:25:36.625 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:25:36.626 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:25:36.627 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2025-12-11 20:26:14.776 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 20:26:14.865 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.05473730101033961
0.0547025089800569

2025-12-11 20:27:09.283 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 20:27:09.285 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP5-H_2030.xlsx
'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None)
TD applied to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, CA-QC, None) to 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None)>
for the activity 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' (kWh, CA-QC, None),it's under SSP-SSP1-VLLO, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 20:33:05.903 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 20:36:10.078 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 20:36:34.168 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 20:36:36.887 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 20:36:38.629 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...
2025-12-11 20:36:38.734 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:36:38.738 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:36:38.740 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:36:38.741 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:36:38.741 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.

Calculation count: 1

2025-12-11 20:37:25.588 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 20:37:25.770 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.015534852035032371
0.017940049173005287

2025-12-11 20:38:13.173 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 20:38:13.175 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, CA-QC, SSP1-VLLO, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_CA-QC_SSP1-VLLO_2050.xlsx
'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' (kWh, RoW, None),it's under SSP-SSP5-H, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP585', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 20:42:57.033 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 20:47:55.266 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 20:48:19.928 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 20:48:23.059 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 20:48:24.823 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 20:48:25.026 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:48:25.031 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:48:25.033 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:48:25.036 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:48:25.038 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 20:49:09.259 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 20:49:09.372 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.04519814216649301
0.04550736621717622

2025-12-11 20:50:14.954 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 20:50:14.955 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP5-H, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP5-H_2050.xlsx
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' (kWh, RoW, None),it's under SSP-SSP2-M, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 20:54:45.330 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 21:00:11.115 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 21:00:34.073 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 21:00:36.986 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 21:00:39.093 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 21:00:39.229 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:00:39.233 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:00:39.234 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:00:39.235 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:00:39.237 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:01:20.242 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 21:01:20.436 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.05584781277644521
0.055970076047754426

2025-12-11 21:02:08.266 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 21:02:08.269 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP2-M_2030.xlsx
'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' (kWh, RoW, None),it's under SSP-SSP2-M, year-2050
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP245', 'MY2050', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 21:07:59.819 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 21:12:05.392 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 21:12:30.618 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 21:12:34.235 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 21:12:36.390 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 21:12:36.609 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:12:36.612 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:12:36.616 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:12:36.618 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:12:36.619 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:13:16.139 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 21:13:16.260 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.04970101534488699
0.050581337372865666

2025-12-11 21:14:30.241 | INFO     | bw_timex.timex_lca:__init__:114 - Initializing TimexLCA object...
2025-12-11 21:14:30.242 | INFO     | bw_timex.timex_lca:__init__:136 - Collecting node infos...

✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP2-M, 2050' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP2-M_2050.xlsx
'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)
TD applied to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' → Exchange: 1 kilowatt hour 'electricity production, hydro, reservoir, non-alpine region' (kilowatt hour, RoW, None) to 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None)>
for the activity 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' (kWh, RoW, None),it's under SSP-SSP1-VLLO, year-2030
 we'll use LCIA ('Climate Change prospective GWP100', 'SSP119', 'MY2030', 'pGWP100 - fixed-AGWPCO2')  with background database.datetime = {'ei_cutoff_3.11_image_SSP1-VLLO_2030 2025-11-24': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP1-VLLO_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP2-M_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2030 2025-11-22': datetime.datetime(2030, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2040 2025-11-22': datetime.datetime(2040, 1, 1, 0, 0), 'ei_cutoff_3.11_image_SSP5-H_2050 2025-11-22': datetime.datetime(2050, 1, 1, 0, 0), 'elec_hydro_reservoir_foreground': 'dynamic'}

2025-12-11 21:21:27.237 | INFO     | bw_timex.timex_lca:build_timeline:216 - No edge filter function provided. Skipping all edges in background databases.
2025-12-11 21:27:08.980 | INFO     | bw_timex.timex_lca:build_timeline:232 - Calculating base LCA...
2025-12-11 21:27:33.472 | INFO     | bw_timex.timex_lca:build_timeline:242 - Creating activity time mapping...
2025-12-11 21:27:36.583 | INFO     | bw_timex.timeline_builder:__init__:99 - Traversing supply chain graph...

Starting graph traversal

2025-12-11 21:27:38.404 | INFO     | bw_timex.timeline_builder:build_timeline:142 - Building timeline...

Calculation count: 1

2025-12-11 21:27:38.587 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:27:38.591 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2026-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:27:38.595 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2027-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:27:38.597 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2028-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:27:38.598 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:522 - Reference date 2029-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2025-12-11 21:28:26.391 | INFO     | bw_timex.timex_lca:lci:360 - Expanding matrices...
2025-12-11 21:28:26.576 | INFO     | bw_timex.timex_lca:lci:379 - Calculating dynamic inventory...

0.05726559498803554
0.057505282300774264
✔ Exported dynamic inventory DF for 'market for electricity, hydro, high voltage, RoW, SSP1-VLLO, 2030' → dp-LCI_output/hydro_dpLCI_v2_reservoir/market_for_electricity_hydro_high_voltage_RoW_SSP1-VLLO_2030.xlsx
✔ Saved dp_results dictionary → dp-LCI_output/hydro_dpLCI_v2_reservoir/hydro_v2_reservoir_dp_results_MY2030_2050.pkl